const fs = require('fs')
const path = require('path')
const src = path.join(__dirname, 'STD HIV Logo 2024_6Color_OL_WTbkg.png')
const destDir = path.join(__dirname, 'public')
const dest = path.join(destDir, 'ptc-logo.png')
if (!fs.existsSync(destDir)) fs.mkdirSync(destDir)
fs.copyFileSync(src, dest)
console.log('Done: copied to public/ptc-logo.png')
const http = require('http')
http.createServer((req, res) => res.end('done')).listen(9997)
